### ISSUE TITLE
Support for instrumentation 

### ISSUE THREAD

**Issue by aianta** [tibor-kocsis/vertx-graphql-utils#1]
I'm trying to hook up my [dataloaders](https://github.com/engagingspaces/vertx-dataloader) to dispatch once all my fetchers are done. It seems the best way to go about doing this is through instrumentation as described [here](http://graphql-java.readthedocs.io/en/v6/batching.html). 

What do you think the best approach to something like this would be? Add an additional parameter to `AsyncGraphQLExecImpl` 's constructor for an optional list of instrumentions to build the GraphQL object with?

**Comment by tibor-kocsis** [comment]
I added a new static factory method to GraphQLPostRouteHandler and to AsyncGraphQLExec which takes a GraphQL.Builder as parameter. With this approach any new features in the following GraphQL releases will be supported. Please take a look it, and if it's ok for you too, i will push a new releease.

Commits are: 6c89ddcc1c975f55be1709c5bcb71d786c94b8e0 6d5fd4e6701109baf880466f4a6e009223be711d

**Comment by tibor-kocsis** [comment]
the change is in version 2.0.6 now
